### ISSUE TITLE
Question: What is the meaning of f_0 in ellipse equation

### ISSUE THREAD

**Issue by EmmaThompson123** [Hiroaki-K4/3d_computer_vision#25]
HI, I saw there is a variable `f_0` in the ellipse equation under the <elliptic_analysis> folder, [ellipse's wikipedia](https://en.wikipedia.org/wiki/Ellipse) has not this coefficient, so I don't know what is the meaning of it

**Comment by Hiroaki-K4** [comment]
@wadeok 
Hi. Thank you for the question.
f_0 is a constant that adjusts the scale. Theoretically, 1 is fine, but for numerical calculations using a finite-length computer, it is convenient for x/f_0,y/f_0 to be around 1. If x or y are very large, the values may exceed what the computer can calculate during the calculation. Therefore, the length of one side of the image is sometimes set to f_0.

**Comment by EmmaThompson123** [comment]
Got it, now I know the necessity of f_0 and the best practice of it ~
