### ISSUE TITLE
Feature Request: Compatibilty for Python <3.8

### ISSUE THREAD

**Issue by testor2897** [Hiroaki-K4/3d_computer_vision#26]
Hi,

As I use Python 3.79 there is no implementation of the mast.dist() function.
It would be very kind to add a pre Python 3.8 addition to the code utils.py:

```
# standard import section
import math

import numpy as np
import sympy
from matplotlib import pyplot as plt
from tqdm import tqdm

# implement a replacement if math.dist() is not defined
try:
    import math.dist
except:
    def dist(a, b):
        return math.sqrt((a[0]-b[0])**2+(a[1]-b[1])**2)
    math.dist = dist

```

Greetings,

Sebastian

**Comment by Hiroaki-K4** [comment]
@testor2897 
Hi.
I don't want the code to handle the environment, so could you create the environment using something like pyenv?
thanks.
